"""Protocol for run storage backends."""
from __future__ import annotations

from typing import Protocol


class RunStorageProtocol(Protocol):
    def save_run(self, run_id: str, status: str, data: dict | None = None) -> None: ...
    def get_run(self, run_id: str) -> dict | None: ...
    def list_runs(self) -> list[dict]: ...
    def delete_run(self, run_id: str) -> None: ...
    def cleanup_expired(self, ttl_seconds: int) -> int: ...
